### PR TITLE
Use standard flags to link libgcc, libc

### PR DESCRIPTION
**Pull request by PikalaxALT**

### CODE REVIEW

**Comment by yenatch** [comment]
pret/pokeemerald#178 breaks windows builds

**Comment by camthesaxman** [comment]
I don't really see the point of this, if you have to link the archives directly on Windows. It's better to be consistent and do the same thing on Linux, OS X, and Windows.

**Comment by PikalaxALT** [comment]
@camthesaxman The hope is that the devkitARM team will resolve the bug that prevents traditional library linking in cygwin.

**Comment by PikalaxALT** [comment]
This PR is obsolete.

**Pull request closed without merging**
