### PR TITLE
mid2agb improvements

### PR DESCRIPTION
**Pull request by camthesaxman**
I've gotten two midi songs so far to match out of 8 that I tried. I have trouble dumping some of them to get the same compression and divide the rests the same way.

### CODE REVIEW

**Comment by drifloony** [comment]
There are a few problems with the implementation of running status.

1. The running status will be corrupted by FindNoteEnd. It needs to be saved/restored.
2. The running status is carried over from previous tracks.
2. Events with status 0xF0 or greater shouldn't affect the running status.

**Comment by iimarckus** [comment]
I can play them just fine with FluidSynth.

**Comment by camthesaxman** [comment]
Others have said that they don't play in Winamp and newer versions of Windows Media Player. I have yet to try those programs. I also tried Timidity on Linux Mint, but it refused to play any sound because it didn't detect the instruments, even though the program change events are there. I'd like to know what's causing the incompatibilities with some MIDI players.

**Comment by iimarckus** [comment]
They work fine for me in Timidity too. I don’t pretend to know how MIDI/soundfonts work or anything, but I had no problems with Timidity or Fluidsynth except the instruments didn’t sound like the GBA.

**Comment by camthesaxman** [comment]
I ran a script that tested all of my dumped MIDI files, and I added all of the ones that matched.

**Comment by drifloony** [comment]
The MIDI files seem to be silent in the Windows 10 version of Windows Media Player.

**Comment by camthesaxman** [comment]
Try these MIDI files and see if they work now.

**Comment by drifloony** [comment]
I still don't hear anything.

**Comment by camthesaxman** [comment]
Hmm... I'm not sure what's causing the incompatibility. The files play fine for me on WMP10, MidiYodi, Timidity, SeNSSoFT Midi Player (Windows Phone app), and my Suzuki G-33 keyboard, and can be imported into MuseScore. WMP12 seems to be the only program I've tried that has a problem with these files, and I don't know enough about MIDI to figure out what's causing it to be silent.

**Comment by camthesaxman** [comment]
I guess this PR is obsolete now that Diego fixed the midi issues in pokeemerald. It would be better to apply those mid2agb changes to pokeruby and pokefirered.

**Comment by PikalaxALT** [comment]
If this PR is obsolete, then please close it without merge.

**Pull request closed without merging**
