### PR TITLE
Fix German Sapphire's Default Nr.1 Player Names

### PR DESCRIPTION
**Pull request by JaceCearK1**

### CODE REVIEW

**Comment by yenatch** [comment]
@marijnvdwerf is this correct?

**Comment by JaceCearK1** [comment]
These screenshots should be enough proof, right?
pokemonsaphir_01
pokemonsaphir_02
pokemonsaphir_03

**Comment by ProjectRevoTPP** [comment]
padz is slow

**Comment by JaceCearK1** [comment]
@ProjectRevoTPP padz?

**Comment by yenatch** [comment]
It's not that I don't believe you, just that I can't verify it myself. It's possible the names differ between revisions.

**Comment by camthesaxman** [comment]
It's unlikely that they changed the names between revisions. At least this gets us closer to building a complete German ROM.

**Comment by iimarckus** [comment]
The screenshoto match both “Pokemon - Saphir-Edition (Germany)" and "Pokemon - Saphir-Edition (Germany) (Rev 1)" from No-Intro.

**Comment by yenatch** [comment]
Thanks.

**Pull request merged**
