### PR TITLE
split out src/ directory into categorized subdirectories.

### PR DESCRIPTION
**Pull request by ProjectRevoTPP**
Please leave comments as to what files should go where, but I think this is a decent starting point.

### CODE REVIEW

**Comment by camthesaxman** [comment]
libc, m4a, siirtc, and agb_flash don't really belong in engine, since those are SDK provided libraries, and not part of Pokemon Ruby. Having a libs directory for those would probably be a good idea.

**Comment by ProjectRevoTPP** [comment]
I tried to put them in lib/ and couldnt figure out how to do it.

**Comment by camthesaxman** [comment]
How is that any different from putting it in the engine subdir? Just make another subdir called libs.

**Comment by ProjectRevoTPP** [comment]
I mean, I tried to put it in libs/ rather than src/libs.

**Comment by ProjectRevoTPP** [comment]
I am debating on a menu/ folder as well. Thoughts?

**Pull request closed without merging**
