### PR TITLE
decompile more pokedex functions

### PR DESCRIPTION
**Pull request by camthesaxman**
I'm having trouble getting some functions to match.

### CODE REVIEW

**Comment by YamaArashi** [comment]
I took a look at those and yeah, they seem pretty strange. We might not be able to get everything to match.

**Comment by camthesaxman** [comment]
I tried forcibly spilling the variables using &, and tried an array, and a struct, but the array seems to match the closest.

**Comment by YamaArashi** [comment]
Yes. I saw those issues. I am not sure why you think the loop counter variable is a u16 in case 1 of the switch in sub_808D690. The condition branch `ble _0808D896` uses a signed comparison. It still won't match if you use s16, though.

**Comment by camthesaxman** [comment]
I fixed up some mistakes to where it matches more closely. Still not 100%, though.

**Pull request merged**
